// <auto-generated />
using System;
using CarRental.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarRental.Data.Migrations
{
    [DbContext(typeof(CarRentalDbContext))]
    partial class CarRentalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarRental.Data.Entities.ClientAccount", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FullName");

                    b.Property<string>("Phone");

                    b.HasKey("ClientId");

                    b.ToTable("ClientAccounts");
                });

            modelBuilder.Entity("CarRental.Data.Entities.Rezervation", b =>
                {
                    b.Property<int>("RezervationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("CancelationFeeRate");

                    b.Property<decimal?>("CancellationFee");

                    b.Property<string>("CarPlateNumber");

                    b.Property<int>("CarType");

                    b.Property<int>("ClientId");

                    b.Property<decimal>("DepositFee");

                    b.Property<bool>("IsCancelled");

                    b.Property<bool>("IsPickedUp");

                    b.Property<bool>("IsReturned");

                    b.Property<DateTime?>("PickUpDate");

                    b.Property<decimal>("RentaltFee");

                    b.Property<DateTime?>("ReturnDate");

                    b.HasKey("RezervationId");

                    b.HasIndex("ClientId");

                    b.ToTable("Rezervations");
                });

            modelBuilder.Entity("CarRental.Data.Entities.Rezervation", b =>
                {
                    b.HasOne("CarRental.Data.Entities.ClientAccount", "ClientAccount")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
